### ISSUE TITLE
Write unit tests for the webserver API's

### ISSUE THREAD

**Issue by gmm97** [DD2480-Team/DD2480#71]
Research on how to unit test the functionality for the webserver and test Flask API endpoints. Refer to the following docs for testing flask endpoints: https://flask.palletsprojects.com/en/1.0.x/testing/

1) Write individual unit tests for each handler by creating a mock/test context
2) Make assertions throughout the unit tests

sub-issue: 
- [x] https://github.com/DD2480-Team/DD2480/issues/75#issue-1127633089

**Comment by jacobmimms** [comment]
closed with #110
